services:
#   To connect to the db: host.docker.internal:5432
  pgadmin:
    image: dpage/pgadmin4:8.12.0
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@fcai.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"

  postgres_db:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: security_demo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: