security:
  jwt:
    secret-key: 406a970f5fdd329ef30bb1b0e6205f7692d69647322a926bd30ac84ab1c6b8fa
    expiration-time: 3600000

spring:
  application:
    name: security-demo

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    url: jdbc:postgresql://localhost:5432/security_demo
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
